### Borrar cache
GET /prueba-ave-back/public/api/clear-cache HTTP/1.1
Host: localhost


### Autenticacion
POST /prueba-ave-back/public/api/auth HTTP/1.1
Content-Type: application/json
Host: localhost
Content-Length: 47
{
	"user": "root",
	"password": "1234567890"
}

### Crear un usuario
POST /prueba-ave-back/public/api/register?= HTTP/1.1
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJsb2NhbGhvc3QiLCJleHAiOjE2OTExNzM0OTIsImF1ZCI6ImZkZGY5YjU5NzNiMTI4ZjkzMWEzZmQyMTlmNjllMDgyIiwidXNlciI6InJvb3QiLCJkcyI6InVzZXIgcm9vdCIsImlkIjoxLCJyb2wiOiJTdXBlckFkbWluIn0.Vd7ZBIpXfP08aCjpLwMR0d_A9ddm3pZKjxB0tNAYbg9N7PYIg6zQ5FWL8oeH8ZV7uhOFDol5e0SYej1Xv8QKheb_WAMjaVgr7kjHp9wss4H-dB79iS32kpiWIIc8x6_a4An1U-6pDKdN0_kLy3hfZsIi5OQLhaUwgpBpOyXFFBA
Host: localhost
Content-Length: 74

{
	"user": "menito2",
	"password": "12345678",
	"name": "menito2 de tales"
}


### Auto registro de cliente
POST /prueba-ave-back/public/api/register?= HTTP/1.1
Content-Type: application/json
Host: localhost
Content-Length: 155

{
	"user": "Daniel",
	"password": "12345678",
	"name": "Daniel camilo",
	"lastname": "Perez",
	"email": "daniel@mail.com",
	"document": "DOC-100001"
}

### Listar todos los clientes
GET /prueba-ave-back/public/api/client?= HTTP/1.1
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJsb2NhbGhvc3QiLCJleHAiOjE2OTExNzM0OTIsImF1ZCI6ImZkZGY5YjU5NzNiMTI4ZjkzMWEzZmQyMTlmNjllMDgyIiwidXNlciI6InJvb3QiLCJkcyI6InVzZXIgcm9vdCIsImlkIjoxLCJyb2wiOiJTdXBlckFkbWluIn0.Vd7ZBIpXfP08aCjpLwMR0d_A9ddm3pZKjxB0tNAYbg9N7PYIg6zQ5FWL8oeH8ZV7uhOFDol5e0SYej1Xv8QKheb_WAMjaVgr7kjHp9wss4H-dB79iS32kpiWIIc8x6_a4An1U-6pDKdN0_kLy3hfZsIi5OQLhaUwgpBpOyXFFBA
Host: localhost

### Buscar un cliente por id
GET /prueba-ave-back/public/api/client/5?= HTTP/1.1
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJsb2NhbGhvc3QiLCJleHAiOjE2OTExNzM0OTIsImF1ZCI6ImZkZGY5YjU5NzNiMTI4ZjkzMWEzZmQyMTlmNjllMDgyIiwidXNlciI6InJvb3QiLCJkcyI6InVzZXIgcm9vdCIsImlkIjoxLCJyb2wiOiJTdXBlckFkbWluIn0.Vd7ZBIpXfP08aCjpLwMR0d_A9ddm3pZKjxB0tNAYbg9N7PYIg6zQ5FWL8oeH8ZV7uhOFDol5e0SYej1Xv8QKheb_WAMjaVgr7kjHp9wss4H-dB79iS32kpiWIIc8x6_a4An1U-6pDKdN0_kLy3hfZsIi5OQLhaUwgpBpOyXFFBA
Host: localhost

### Registrar cliente
POST /prueba-ave-back/public/api/client/create?= HTTP/1.1
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJsb2NhbGhvc3QiLCJleHAiOjE2OTExNzM0OTIsImF1ZCI6ImZkZGY5YjU5NzNiMTI4ZjkzMWEzZmQyMTlmNjllMDgyIiwidXNlciI6InJvb3QiLCJkcyI6InVzZXIgcm9vdCIsImlkIjoxLCJyb2wiOiJTdXBlckFkbWluIn0.Vd7ZBIpXfP08aCjpLwMR0d_A9ddm3pZKjxB0tNAYbg9N7PYIg6zQ5FWL8oeH8ZV7uhOFDol5e0SYej1Xv8QKheb_WAMjaVgr7kjHp9wss4H-dB79iS32kpiWIIc8x6_a4An1U-6pDKdN0_kLy3hfZsIi5OQLhaUwgpBpOyXFFBA
Content-Type: application/json
Host: localhost
Content-Length: 155

{
	"user": "andres 3",
	"password": "12345678",
	"name": "andres3 camilo",
	"lastname": "Perez",
	"email": "andres333@mail.com",
	"document": "sp-100147"
}

### Actualizar datos del cliente
PATCH /prueba-ave-back/public/api/client/update/5?= HTTP/1.1
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJsb2NhbGhvc3QiLCJleHAiOjE2OTExNzM0OTIsImF1ZCI6ImZkZGY5YjU5NzNiMTI4ZjkzMWEzZmQyMTlmNjllMDgyIiwidXNlciI6InJvb3QiLCJkcyI6InVzZXIgcm9vdCIsImlkIjoxLCJyb2wiOiJTdXBlckFkbWluIn0.Vd7ZBIpXfP08aCjpLwMR0d_A9ddm3pZKjxB0tNAYbg9N7PYIg6zQ5FWL8oeH8ZV7uhOFDol5e0SYej1Xv8QKheb_WAMjaVgr7kjHp9wss4H-dB79iS32kpiWIIc8x6_a4An1U-6pDKdN0_kLy3hfZsIi5OQLhaUwgpBpOyXFFBA
Content-Type: application/json
Host: localhost
Content-Length: 56

{
	"name": "juan andres3 camilo",
	"lastname": "Perez"
}


### Eliminacion lógica de cliente
DELETE /prueba-ave-back/public/api/client/delete/5?= HTTP/1.1
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJsb2NhbGhvc3QiLCJleHAiOjE2OTExNzM0OTIsImF1ZCI6ImZkZGY5YjU5NzNiMTI4ZjkzMWEzZmQyMTlmNjllMDgyIiwidXNlciI6InJvb3QiLCJkcyI6InVzZXIgcm9vdCIsImlkIjoxLCJyb2wiOiJTdXBlckFkbWluIn0.Vd7ZBIpXfP08aCjpLwMR0d_A9ddm3pZKjxB0tNAYbg9N7PYIg6zQ5FWL8oeH8ZV7uhOFDol5e0SYej1Xv8QKheb_WAMjaVgr7kjHp9wss4H-dB79iS32kpiWIIc8x6_a4An1U-6pDKdN0_kLy3hfZsIi5OQLhaUwgpBpOyXFFBA
Host: localhost
